name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2

      - name: Build the application
        uses: ./.github/actions/build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            product/BaCon-linux
            product/BaCon-macos
            product/BaCon-win.exe
          body: '# ${{ steps.get_version.outputs.version }} release'
        
